CREATE TABLE TB_TIPO (
ID_TIPO INTEGER PRIMARY KEY,
DS_RECEITA VARCHAR2(50),
STATUS VARCHAR2(10)
);

CREATE TABLE TB_RECEITA (
ID_RECEITA INTEGER PRIMARY KEY,
DT_ANO DATE,
VL_RECEITA NUMBER(15,2),
ID_TIPO INTEGER REFERENCES TB_TIPO(ID_TIPO)
); 

CREATE SEQUENCE SQ_TB_RECEITA
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 30;  